### ISSUE TITLE
[TheWitcher] Dark mode issues

### ISSUE THREAD

**Issue by gnompsky** [Stexinator/roll20-character-sheets#346]
Roll20 dark mode overrides some font colours in the sheet despite the sheet not changing anything else for dark mode. This results in some areas where the text goes too light for the background colour.

I've only spotted this on `<label>` elements so far but there may be others.

Because of the way they've applied dark mode changes, it'll override any default values in the sheet. Anywhere you adjust font colour on a label you'll also need to apply that with the dark mode selector too as follows:
```css
/* This is needed to override Roll20's dark mode */
.sheet-darkmode .characterviewer label.gear-item-name
    color: #FFF; /* May also need !important here, not checked */
}

/* This already exists in your styles */
label.gear-item-name {
    display: inline-block;
    text-align: center;
    width: 130px;
    font-weight: 1;
    font-size: 12px;
    color: #FFF;
}
```
## Examples
![image](https://user-images.githubusercontent.com/2944741/185353649-4d2758bd-e23a-4f94-825c-814b542ebbf1.png)
![image](https://user-images.githubusercontent.com/2944741/185353996-7485a938-9c83-4ecc-81f8-c0725d11944c.png)
![image](https://user-images.githubusercontent.com/2944741/185354117-59770b4f-b0b4-4dcb-a1f8-415ec8a8bfe7.png)
